# Generated by Django 5.2 on 2026-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0004_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "permissions": [
                    ("view_all_tickets", "مشاهده تیکت\u200cها"),
                    ("create_ticket", "ایجاد تیکت"),
                    ("reply_ticket", "پاسخ به تیکت"),
                    ("change_ticket_status", "تغییر وضعیت تیکت"),
                    ("assign_ticket", "تخصیص تیکت"),
                ]
            },
        ),
    ]
