# Generated by Django 5.2 on 2026-09-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان نامه")),
                ("content", models.TextField(verbose_name="متن نامه")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("in", "نامه وارده"),
                            ("out", "نامه صادره"),
                            ("internal", "نامه داخلی"),
                        ],
                        max_length=20,
                        verbose_name="نوع نامه",
                    ),
                ),
                ("sent_to", models.CharField(max_length=200, verbose_name="گیرنده")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sent", "ارسال شده"),
                            ("received", "دریافت شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letters/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارجاع به",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نامه اداری",
                "verbose_name_plural": "نامه\u200cهای اداری",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_all_letters", "مشاهده همه نامه\u200cها"),
                    ("create_letter", "ایجاد نامه"),
                    ("edit_letter", "ویرایش نامه"),
                    ("delete_letter", "حذف نامه"),
                    ("send_letter", "ارسال نامه"),
                    ("assign_letter", "ارجاع نامه"),
                ],
            },
        ),
    ]
