# Generated by Django 5.2 on 2026-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internalletter",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_all_letters", "مشاهده همه نامه\u200cها"),
                    ("create_letter", "ایجاد نامه"),
                    ("edit_letter", "ویرایش نامه"),
                    ("delete_letter", "حذف نامه"),
                    ("assign_letter", "ارجاع نامه"),
                    ("approve_letter", "تأیید نامه"),
                    ("reject_letter", "رد نامه"),
                ],
                "verbose_name": "نامه اداری",
                "verbose_name_plural": "نامه\u200cهای اداری",
            },
        ),
        migrations.AlterField(
            model_name="internalletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تأیید شده"),
                    ("rejected", "رد شده"),
                ],
                default="draft",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
