# Generated by Django 5.2 on 2026-10-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_automation", "0002_alter_internalletter_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internalletter",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تأیید"
            ),
        ),
        migrations.AddField(
            model_name="internalletter",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_letters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأیید توسط",
            ),
        ),
        migrations.AddField(
            model_name="internalletter",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ ارجاع"
            ),
        ),
        migrations.AddField(
            model_name="internalletter",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_letters_by_me",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ارجاع توسط",
            ),
        ),
        migrations.AddField(
            model_name="internalletter",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ رد"),
        ),
        migrations.AddField(
            model_name="internalletter",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_letters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رد توسط",
            ),
        ),
    ]
